package com.communer.Utils;

import java.util.HashMap;
import java.util.Map;

/**
 * Created by יובל on 03/09/2015.
 */
public class CountriesPrefixes {

    private static Map<String, String> map = new HashMap<String, String>();

    public static String getPhone(String code) {
        return map.get(code);
    }
    public static Map<String, String> getAll(){
        return map;
    }

    static {
        map.put("Canada","+1");
        map.put("China","86");
        map.put("France","33");
        map.put("Germany","49");
        map.put("India","+91");
        map.put("Japan","+81");
        map.put("Pakistan","+92");
        map.put("United Kingdom","+44");
        map.put("United States","+1");
        map.put("Abkhazia","+7 840");
        map.put("Abkhazia","+7 940");
        map.put("Afghanistan"           ,                       "+93");
        map.put("Albania"            ,                          "+355");
        map.put("Algeria"  ,                                    "+213");
        map.put("American Samoa"    ,                          "+1 684");
        map.put("Andorra"        ,                              "+376");
        map.put("Angola"         ,                              "+244");
        map.put("Anguilla"       ,                              "+1 264");
        map.put("Antigua and Barbuda"  ,                        "+1 268");
        map.put("Argentina"               ,                     "+54");
        map.put("Armenia"                 ,                     "+374");
        map.put("Aruba"                    ,                    "+297");
        map.put("Ascension"                 ,                   "+247");
        map.put("Australia"                        ,            "+61");
        map.put("Australian External Territories"     ,         "+672");
        map.put("Austria"                     ,                 "+43");
        map.put("Azerbaijan"   ,                                "+994");
        map.put("Bahamas" ,                                     "+1 242");
        map.put("Bahrain"   ,                                   "+973");
        map.put("Bangladesh"  ,                                 "+880");
        map.put("Barbados"    ,                                 "+1 246");
        map.put("Barbuda"      ,                                "+1 268");
        map.put("Belarus"    ,                                  "+375");
        map.put("Belgium"    ,                                  "+32");
        map.put("Belize"     ,                                  "+501");
        map.put("Benin"      ,                                  "+229");
        map.put("Bermuda"    ,                                  "+1 441");
        map.put("Bhutan"        ,                               "+975");
        map.put("Bolivia"      ,                                "+591");
        map.put("Bosnia and Herzegovina"    ,                   "+387");
        map.put("Botswana"             ,                        "+267");
        map.put("Brazil"               ,                        "+55");
        map.put("British Indian Ocean Territory"      ,        "+246");
        map.put("British Virgin Islands"     ,                  "+1 284");
        map.put("Brunei"                ,                       "+673");
        map.put("Bulgaria"               ,                      "+359");
        map.put("Burkina Faso"            ,                     "+226");
        map.put("Burundi"                 ,                     "+257");
        map.put("Cambodia" ,                                 "+855");
        map.put("Cameroon",                                     "+237");
        map.put("Canada"    ,                                   "+1");
        map.put("Cape Verde"   ,                                "+238");
        map.put("Cayman Islands"   ,                            "+ 345");
        map.put("Central African Republic"   ,                  "+236");
        map.put("Chad"              ,                           "+235");
        map.put("Chile"             ,                           "+56");
        map.put("China"             ,                           "+86");
        map.put("Christmas Island"      ,                       "+61");
        map.put("Cocos-Keeling Islands"     ,                   "+61");
        map.put("Colombia"   ,                                  "+57");
        map.put("Comoros"        ,                              "+269");
        map.put("Congo"    ,                                    "+242");
        map.put("Congo, Dem. Rep. of (Zaire)"      ,            "+243");
        map.put("Cook Islands"        ,                         "+682");
        map.put("Costa Rica"         ,                          "+506");
        map.put("Ivory Coast"   ,                               "+225");
        map.put("Croatia"     ,                                 "+385");
        map.put("Cuba"        ,                                 "+53");
        map.put("Curacao"       ,                               "+599");
        map.put("Cyprus"        ,                               "+537");
        map.put("Czech Republic"  ,                             "+420");
        map.put("Denmark"        ,                              "+45");
        map.put("Diego Garcia"     ,                            "+246");
        map.put("Djibouti"      ,                               "+253");
        map.put("Dominica"          ,                           "+1 767");
        map.put("Dominican Republic"    ,                       "+1 809");
        map.put("Dominican Republic" ,                          "+1 829");
        map.put("Dominican Republic"   ,                        "+1 849");
        map.put("East Timor"        ,                           "+670");
        map.put("Easter Island"      ,                          "+56");
        map.put("Ecuador"         ,                             "+593");
        map.put("Egypt"          ,                              "+20");
        map.put("El Salvador"          ,                        "+503");
        map.put("Equatorial Guinea"    ,                        "+240");
        map.put("Eritrea"      ,                                "+291");
        map.put("Estonia"    ,                                  "+372");
        map.put("Ethiopia"     ,                                "+251");
        map.put("Falkland Islands"  ,                           "+500");
        map.put("Faroe Islands"    ,                            "+298");
        map.put("Fiji"  ,                                       "+679");
        map.put("Finland"    ,                                  "+358");
        map.put("France"         ,                              "+33");
        map.put("French Antilles"    ,                          "+596");
        map.put("French Guiana"     ,                           "+594");
        map.put("French Polynesia"    ,                         "+689");
        map.put("Gabon"     ,                                   "+241");
        map.put("Gambia"       ,                                "+220");
        map.put("Georgia"      ,                                "+995");
        map.put("Germany"        ,                              "+49");
        map.put("Ghana"        ,                                "+233");
        map.put("Gibraltar"       ,                             "+350");
        map.put("Greece"          ,                             "+30");
        map.put("Greenland"     ,                               "+299");
        map.put("Grenada"      ,                                "+1 473");
        map.put("Guadeloupe"  ,                                 "+590");
        map.put("Guam"        ,                                 "+1 671");
        map.put("Guatemala"    ,                                "+502");
        map.put("Guinea"         ,                              "+224");
        map.put("Guinea-Bissau"     ,                           "+245");
        map.put("Guyana"           ,                            "+595");
        map.put("Haiti"           ,                             "+509");
        map.put("Honduras"        ,                             "+504");
        map.put("Hong Kong SAR China"  ,                        "+852");
        map.put("Hungary"    ,                                  "+36");
        map.put("Iceland"  ,                                    "+354");
        map.put("India"     ,                                   "+91");
        map.put("Indonesia"  ,                                  "+62");
        map.put("Iran"       ,                                 "+98");
        map.put("Iraq"        ,                                 "+964");
        map.put("Ireland"      ,                                "+353");
        map.put("Israel"       ,                                "+972");
        map.put("Italy"        ,                                "+39");
        map.put("Jamaica"       ,                               "+1 876");
        map.put("Japan"       ,                                 "+81");
        map.put("Jordan"       ,                                "+962");
        map.put("Kazakhstan"   ,                                "+7 7");
        map.put("Kenya"          ,                              "+254");
        map.put("Kiribati"       ,                              "+686");
        map.put("North Korea"     ,                             "+850");
        map.put("South Korea"      ,                            "+82");
        map.put("Kuwait"             ,                          "+965");
        map.put("Kyrgyzstan"       ,                            "+996");
        map.put("Laos" ,                                        "+856");
        map.put("Latvia"     ,                                  "+371");
        map.put("Lebanon"  ,                                    "+961");
        map.put("Lesotho"    ,                                  "+266");
        map.put("Liberia"   ,                                   "+231");
        map.put("Libya"   ,                                     "+218");
        map.put("Liechtenstein"   ,                             "+423");
        map.put("Lithuania"       ,                             "+370");
        map.put("Luxembourg"      ,                             "+352");
        map.put("Macau SAR China"   ,                           "+853");
        map.put("Macedonia"     ,                               "+389");
        map.put("Madagascar"    ,                               "+261");
        map.put("Malawi"     ,                                  "+265");
        map.put("Malaysia"      ,                               "+60");
        map.put("Maldives"   ,                                  "+960");
        map.put("Mali"       ,                                  "+223");
        map.put("Malta"       ,                                 "+356");
        map.put("Marshall Islands"    ,                         "+692");
        map.put("Martinique"       ,                            "+596");
        map.put("Mauritania"       ,                            "+222");
        map.put("Mauritius"     ,                               "+230");
        map.put("Mayotte"       ,                               "+262");
        map.put("Mexico"       ,                                "+52");
        map.put("Micronesia"    ,                               "+691");
        map.put("Midway Island"  ,                              "+1 808");
        map.put("Micronesia"     ,                              "+691");
        map.put("Moldova"       ,                               "+373");
        map.put("Monaco"         ,                              "+377");
        map.put("Mongolia"        ,                             "+976");
        map.put("Montenegro"      ,                             "+382");
        map.put("Montserrat"       ,                            "+1664");
        map.put("Morocco"          ,                            "+212");
        map.put("Myanmar"           ,                           "+95");
        map.put("Namibia"           ,                           "+264");
        map.put("Nauru"        ,                                "+674");
        map.put("Nepal"        ,                                "+977");
        map.put("Netherlands"    ,                              "+31");
        map.put("Netherlands Antilles"   ,                      "+599");
        map.put("Nevis"               ,                        "+1 869");
        map.put("New Caledonia"       ,                         "+687");
        map.put("New Zealand"         ,                         "+64");
        map.put("Nicaragua"    ,                                "+505");
        map.put("Niger"       ,                                 "+227");
        map.put("Nigeria"     ,                                 "+234");
        map.put("Niue"        ,                                 "+683");
        map.put("Norfolk Island"   ,                            "+672");
        map.put("Northern Mariana Islands"  ,                   "+1 670");
        map.put("Norway"   ,                                    "+47");
        map.put("Oman"         ,                                "+968");
        map.put("Pakistan"     ,                                "+92");
        map.put("Palau"          ,                              "+680");
        map.put("Palestinian Territory" ,                       "+970");
        map.put("Panama"    ,                                   "+507");
        map.put("Papua New Guinea"   ,                          "+675");
        map.put("Paraguay"   ,                                  "+595");
        map.put("Peru"        ,                                 "+51");
        map.put("Philippines"   ,                               "+63");
        map.put("Poland"      ,                                 "+48");
        map.put("Portugal"      ,                               "+351");
        map.put("Puerto Rico"     ,                             "+1 787");
        map.put("Puerto Rico"      ,                            "+1 939");
        map.put("Qatar"      ,                                  "+974");
        map.put("Reunion"        ,                              "+262");
        map.put("Romania"       ,                               "+40");
        map.put("Russia"          ,                             "+7");
        map.put("Rwanda"        ,                               "+250");
        map.put("Samoa"        ,                                "+685");
        map.put("San Marino"     ,                              "+378");
        map.put("Saudi Arabia"     ,                            "+966");
        map.put("Senegal"          ,                            "+221");
        map.put("Serbia"           ,                            "+381");
        map.put("Seychelles"        ,                           "+248");
        map.put("Sierra Leone"        ,                         "+232");
        map.put("Singapore"           ,                         "+65");
        map.put("Slovakia"             ,                        "+421");
        map.put("Slovenia"             ,                        "+386");
        map.put("Solomon Islands"        ,                      "+677");
        map.put("South Africa"           ,                      "+27");
        map.put("South Georgia and the South Sandwich Islands" ,"+500");
        map.put("Spain"         ,                               "+34");
        map.put("Sri Lanka"     ,                               "+94");
        map.put("Sudan"           ,                             "+249");
        map.put("Suriname"        ,                             "+597");
        map.put("Swaziland"         ,                           "+268");
        map.put("Sweden"             ,                          "+46");
        map.put("Switzerland"          ,                        "+41");
        map.put("Syria"            ,                            "+963");
        map.put("Taiwan"            ,                           "+886");
        map.put("Tajikistan"        ,                           "+992");
        map.put("Tanzania"            ,                         "+255");
        map.put("Thailand"              ,                       "+66");
        map.put("Timor Leste"             ,                     "+670");
        map.put("Togo"         ,                                "+228");
        map.put("Tokelau"            ,                          "+690");
        map.put("Tonga"                  ,                      "+676");
        map.put("Trinidad and Tobago"       ,                   "+1 868");
        map.put("Tunisia"                      ,                "+216");
        map.put("Turkey"                     ,                  "+90");
        map.put("Turkmenistan"                ,                 "+993");
        map.put("Turks and Caicos Islands"     ,                "+1 649");
        map.put("Tuvalu"      ,                                 "+688");
        map.put("Uganda"           ,                            "+256");
        map.put("Ukraine"           ,                           "+380");
        map.put("United Arab Emirates"    ,                     "+971");
        map.put("United Kingdom"        ,                       "+44");
        map.put("United States"            ,                    "+1");
        map.put("Uruguay"                 ,                     "+598");
        map.put("U.S. Virgin Islands"       ,                   "+1 340");
        map.put("Uzbekistan"          ,                         "+998");
        map.put("Vanuatu"                   ,                   "+678");
        map.put("Venezuela"            ,                        "+58");
        map.put("Vietnam"              ,                        "+84");
        map.put("Wake Island"            ,                      "+1 808");
        map.put("Wallis and Futuna"      ,                      "+681");
        map.put("Yemen"                    ,                    "+967");
        map.put("Zambia"                   ,                    "+260");
        map.put("Zanzibar"                 ,                    "+255");
        map.put("Zimbabwe"                   ,                  "+263");
    }
}
